### ISSUE TITLE
Should aioredis be an optional dependency?

### ISSUE THREAD

**Issue by florimondmanca** [rafalp/async-caches#9]
Hey!

I see that currently `aioredis` is a hard dependency in `setup.py`. Following the Starlette/databases philosophy regarding dependencies, would it be relevant to make it optional, so that `async-caches` can be used for quick prototyping or lightweight in-memory cache setups?

**Comment by rafalp** [comment]
Hi!

I'm not sure - its optional dependency, but without it it makes no sense to use the lib in production envs, isn't it?

**Comment by florimondmanca** [comment]
Thanks for your answer!

Well, if you take the example of Django's [memcached backend](https://docs.djangoproject.com/en/2.2/topics/cache/#memcached), the docs require the user to install memcached before using it.

But I suppose in the current state of things the Redis backend is the only production-compatible one, so it makes some sense to install it right away.

Just wanted to strike the idea, but it's your call really. I'm to close this for now — maybe in the future if more backends are available you could want to have specific installation instructions for each. :-)

**Comment by rafalp** [comment]
> But I suppose in the current state of things the Redis backend is the only production-compatible one, so it makes some sense to install it right away.

Yeah, there's also no hard dependency on any compiled libs or such in `aioredis` like it is the case for database clients that `databases` uses (or maybe I am still living in the past here ;)).

AFAIK there are no dependencies other than `asyncio` to the `aioredis` so I feel its not that much of issue. But if we ever land new backends, we could turn to optional dependencies.

> Thanks for your answer!

I've actually missed it, sorry about that one ;)
